CREATE TABLE NIMASH_TEST_INSTRUCTOR
(
  FIRST_NAME VARCHAR2(45)
, LAST_NAME VARCHAR2(45)
, EMAIL VARCHAR2(45)
, INSTRUCTOR_DETAIL_ID INT
, ID INT NOT NULL
, CONSTRAINT NIMASH_TEST_INSTRUCTOR_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

ALTER TABLE NIMASH_TEST_INSTRUCTOR
ADD CONSTRAINT NIMASH_TEST_INSTRUCTOR_FK1 FOREIGN KEY
(
  INSTRUCTOR_DETAIL_ID
)
REFERENCES NIMASH_TEST_INSTRUCTOR_DETAIL
(
  ID
)
ENABLE;
